quiz_app
language: java
jdk:
- oraclejdk12
before_install:
- mysql -u root -e "CREATE DATABASE quiz_app";
- mysql -u root -e "CREATE USER 'civicsQuiz'@'localhost' IDENTIFIED BY 'usa'";
- mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'civicsQuiz'@'localhost'";
- mysql -u root -e "FLUSH PRIVILEGES";
- mysql -u root -e "CREATE TABLE quiz (id, question, answer, category, subcategory)";
- mysql -u root -e "insert into quiz (id, question, answer, category, subcategory) values (1,'What is the supreme law of the land?', 'the Constitution','American Government', 'Principles of American Democracy'),(2, 'What does the Constitution do?', 'sets up the government|defines the government|protects basic rights of Americans','American Government', 'Principles of American Democracy')";
services:
- mysql
script:
- cd /home/travis/build/zuzannaweichel-accenture/CivicsQuiz
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: bW+4OEYN4da11odvb7cC2EzDUhcCwUDC56w4MFE13BJZwwBImFhYkOhxVywfYFtFcqr43fhXzogoFDQ/uAd4Ie3pyv80onhwxshCS73y2XKnV+N7627kCIFOxhRW+UQjWuqxTlx79yy16al6bj7ZrPZw92j9R/vo53GhQfWp05uJjguh4YKwH7AFI6z0l5SAH8Qg+V5j0qnlY6we+SPcERzncyzXfx5T4D50TmOV++HgbiM5gCvNU0WaA1sQOKJqZW4Q9U0FlAZ/bIZesRyPpHTQIIpDCtKc4gMGoKAuL/olUtNWSMU24mh6mzURfrSAjJO0DSjDRsahOLE13E6fMAMdObvlFU3S1vpRxKpYqhqa4pPQuKy2r8RxPeJwFno5BdKOdUXoZpVzLRWSBz7Xik0/2nsatTrOOdLmkhpKtrIFVFf/cr5LB3FTPDWZ1hEd95uGfO/hCw8yBrCvIbM4zi6n6nlsFa29pEFzwkHFDIw8dADihAV5eePzGXzjvityVYnRM1CDzhWifgtu5AzHP8TYWFOxYBwh1cPz/nmbfMc6RZsjAxYpJqUe434zcsPYk47AWa+HRKkAzxF2ynLQTBWdId+/p6yyEzymMWccyxr8A5pN6iU5Zy0YpMwGwRbc1+8y4y1MzNIZhwj2XE2FPrjSEggSk1nB4cru+WdcUbo=
  app: civics-quiz-api