language: java
jdk:
  - oraclejdk8

# blocklist
branches:
  except:
    - master
    - develop

# safelist
branches:
  only: 
  - theBeginnings

before_install:
  # - mysql -u root < "database/dropdb.sql"
  - mysql -u root < "database/user_and_database.sql"

services:
  - mysql

script:  
  - cd /home/travis/build/zuzannaweichel-accenture/CivicsQuiz
  - mvn test