delete from quiz;

insert into quiz (id, question, answer, category, subcategory) values
(1,'What is the supreme law of the land?', 'the Constitution','American Government', 'Principles of American Democracy'),
(2, 'What does the Constitution do?', 'sets up the government|defines the government|protects basic rights of Americans','American Government', 'Principles of American Democracy'),
(3, 'The idea of self-government is in the first three words of the Constitution. What are these words?', 'We the People','American Government', 'Principles of American Democracy'),
(4, 'What is an amendment?', 'a change (to the Constitution)|an addition (to the Constitution)','American Government', 'Principles of American Democracy'),
(5, 'What do we call the first ten amendments to the Constitution?', 'the Bill of Rights','American Government', 'Principles of American Democracy'),
(6, 'What is one right or freedom from the First Amendment?', 'speech|religion|assembly|press|petition the government','American Government', 'Principles of American Democracy'),
(7, 'How many amendments does the Constitution have?', 'twenty-seven (27)', 'American Government', 'Principles of American Democracy' ),
(8, 'What did the Declaration of Independence do?', 'announced our independence (from Great Britain)|declared our independence (from Great Britain)|said that the United States is free (from Great Britain)', 'American Government', 'Principles of American Democracy'),
(9, 'What are two rights in the Declaration of Independence?', 'life|liberty|pursuit of happiness', 'American Government', 'Principles of American Democracy'),
(10, 'What is freedom of religion?','You can practice any religion, or not practice a religion.', 'American Government', 'Principles of American Democracy'),
(11, 'What is the economic system in the United States?', 'capitalist economy|market economy', 'American Government', 'Principles of American Democracy'),
(12, 'What is the “rule of law”?','Everyone must follow the law.|Leaders must obey the law.|Government must obey the law.|No one is above the law.', 'American Government', 'Principles of American Democracy'),

(13, 'Name one branch or part of the government.', 'Congress|legislative|President|executive|the courts|judicial', 'American Government', 'System of Government'),
(14, 'What stops one branch of government from becoming too powerful?', 'checks and balances|separation of powers', 'American Government', 'System of Government'),
(15, 'Who is in charge of the executive branch?', 'the President', 'American Government', 'System of Government'),
(16, 'Who makes federal laws?', 'Congress, Senate and House (of Representatives)|(U.S. or national) legislature', 'American Government', 'System of Government'),
(17, 'What are the two parts of the U.S. Congress?', 'the Senate and House (of Representatives)', 'American Government', 'System of Government'),
(18, 'How many U.S. Senators are there?','one hundred (100)', 'American Government', 'System of Government'),
(19, 'We elect a U.S. Senator for how many years?','six (6)', 'American Government', 'System of Government'),
(20, 'Who is one of your state’s U.S. Senators now?', 'Ohio - Sherrod Brown (D), Rob Portman(R)', 'American Government', 'System of Government'),
(21, 'The House of Representatives has how many voting members?', 'four hundred thirty-five (435)', 'American Government', 'System of Government'),
(22, 'We elect a U.S. Representative for how many years?','two (2)', 'American Government', 'System of Government'),
(23, 'Name your U.S. Representative', 'Ohio - Joyce Beatty(D), Marcy Kaptur(D)', 'American Government', 'System of Government'),
(24, 'Who does a U.S. Senator represent?', 'all people of the state', 'American Government', 'System of Government'),
(25, 'Why do some states have more Representatives than other states?','(because of) the state’s population|(because) they have more people|(because) some states have more people', 'American Government', 'System of Government'),
(26, 'We elect a President for how many years?','four (4)', 'American Government', 'System of Government'),
(27, 'In what month do we vote for President?','November', 'American Government', 'System of Government'),
(28, 'What is the name of the President of the United States now?', 'Donald Trump', 'American Government', 'System of Government'),
(29, 'What is the name of the Vice President of the United States now?', 'Mike Pence', 'American Government', 'System of Government'),
(30, 'If the President can no longer serve, who becomes President?', 'the Vice President', 'American Government', 'System of Government'),
(31, 'If both the President and the Vice President can no longer serve, who becomes President?', 'the Speaker of the House', 'American Government', 'System of Government'),
(32, 'Who is the Commander in Chief of the military?','the President', 'American Government', 'System of Government'),
(33, 'Who signs bills to become laws?', 'the President', 'American Government', 'System of Government'),
(34, 'Who vetoes bills?', 'the President', 'American Government', 'System of Government'),
(35, 'What does the President’s Cabinet do?', 'advises the President', 'American Government', 'System of Government'),
(36, 'What are two Cabinet-level positions?', 'Secretary of Agriculture|Secretary of Commerce|Secretary of Defense|Secretary of Education|Secretary of Energy|Secretary of Health and Human Services|Secretary of Homeland Security|Secretary of Housing and Urban Development|Secretary of the Interior|Secretary of Labor|Secretary of State|Secretary of Transportation|Secretary of the Treasury|Secretary of Veterans Affairs|Attorney General|Vice President','American Government', 'System of Government'),
(37, 'What does the judicial branch do?','reviews laws|explains laws|resolves disputes (disagreements)|decides if a law goes against the Constitution', 'American Government', 'System of Government'),
(38, 'What is the highest court in the United States?', 'the Supreme Court', 'American Government', 'System of Government'),
(39, 'How many justices are on the Supreme Court?','nine (9)', 'American Government', 'System of Government'),
(40, 'Who is the Chief Justice of the United States now?', 'John Roberts', 'American Government', 'System of Government'),
(41, 'Under our Constitution, some powers belong to the federal government. What is one power of the federal government?', 'to print money|to declare war|to create an army|to make treaties', 'American Government', 'System of Government'),
(42, 'Under our Constitution, some powers belong to the states. What is one power of the states?', 'provide schooling and education|provide protection (police)|provide safety (fire departments)|give a driver’s license|approve zoning and land use', 'American Government', 'System of Government'),
(43, 'Who is the Governor of your state now?', 'Mike DeWine', 'American Government', 'System of Government'),
(44, 'What is the capital of your state?', 'Columbus', 'American Government', 'System of Government'),
(45, 'What are the two major political parties in the United States?','Democratic and Republican', 'American Government', 'System of Government'),
(46, 'What is the political party of the President now?','Republican', 'American Government', 'System of Government'),
(47, 'What is the name of the Speaker of the House of Representatives now?', 'Nancy Pelosi', 'American Government', 'System of Government'),

(48, 'There are four amendments to the Constitution about who can vote. Describe one of them.', 'Citizens eighteen (18) and older (can vote).|You don’t have to pay (a poll tax) to vote.|Any citizen can vote. (Women and men can vote.)|A male citizen of any race (can vote).', 'American Government', 'Rights and Responsibilities'),
(49, 'What is one responsibility that is only for United States citizens?', 'serve on a jury|vote in a federal election', 'American Government', 'Rights and Responsibilities'),
(50, 'Name one right only for United States citizens.', 'vote in a federal election|run for federal office', 'American Government', 'Rights and Responsibilities'),
(51, 'What are two rights of everyone living in the United States?', 'freedom of expression|freedom of speech|freedom of assembly|freedom to petition the government|freedom of religion|the right to bear arms', 'American Government', 'Rights and Responsibilities'),
(52, 'What do we show loyalty to when we say the Pledge of Allegiance?','the United States|the flag', 'American Government', 'Rights and Responsibilities'),
(53, 'What is one promise you make when you become a United States citizen?','give up loyalty to other countries|defend the Constitution and laws of the United States|obey the laws of the United States|serve in the U.S. military (if needed)|serve (do important work for) the nation (if needed)|be loyal to the United States', 'American Government', 'Rights and Responsibilities'),
(54, 'How old do citizens have to be to vote for President?', 'eighteen (18) and older', 'American Government', 'Rights and Responsibilities'),
(55, 'What are two ways that Americans can participate in their democracy?','vote|join a political party|help with a campaign|join a civic group|join a community group|give an elected official your opinion on an issue|call Senators and Representatives|publicly support or oppose an issue or policy|run for office|write to a newspaper', 'American Government', 'Rights and Responsibilities'),
(56, 'When is the last day you can send in federal income tax forms?','April 15', 'American Government', 'Rights and Responsibilities'),
(57, 'When must all men register for the Selective Service?','at age eighteen (18)|between eighteen (18) and twenty-six (26)', 'American Government', 'Rights and Responsibilities'),

(58, 'What is one reason colonists came to America?', 'freedom|political liberty|religious freedom|economic opportunity|practice their religion|escape persecution','American History','Colonial Period and Independence'),
(59, 'Who lived in America before the Europeans arrived?','American Indians|Native Americans','American History','Colonial Period and Independence'),
(60, 'What group of people was taken to America and sold as slaves?','Africans|people from Africa','American History','Colonial Period and Independence'),
(61, 'Why did the colonists fight the British?', 'because of high taxes (taxation without representation)|because the British army stayed in their houses (boarding, quartering)|because they didn’t have self-government','American History','Colonial Period and Independence'),
(62, 'Who wrote the Declaration of Independence?','(Thomas) Jefferson','American History','Colonial Period and Independence'),
(63, 'When was the Declaration of Independence adopted?','July 4, 1776','American History','Colonial Period and Independence'),
(64, 'There were 13 original states. Name three.','nNew Hampshire|Massachusetts|Rhode Island|Connecticut|New York|New Jersey|Pennsylvania|Delaware|Maryland|Virginia|North Carolina|South Carolina|Georgia','American History','Colonial Period and Independence'),
(65, 'What happened at the Constitutional Convention?','The Constitution was written.|The Founding Fathers wrote the Constitution.','American History','Colonial Period and Independence'),
(66, 'When was the Constitution written?','1787','American History','Colonial Period and Independence'),
(67, 'The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.','(James) Madison|(Alexander) Hamilton|(John) Jay|Publius','American History','Colonial Period and Independence'),
(68, 'What is one thing Benjamin Franklin is famous for?','U.S. diplomat|oldest member of the Constitutional Convention|first Postmaster General of the United States|writer of “Poor Richard’s Almanac”|started the first free libraries','American History','Colonial Period and Independence'),
(69, 'Who is the “Father of Our Country”?','(George) Washington','American History','Colonial Period and Independence'),
(70, 'Who was the first President?','(George) Washington','American History','Colonial Period and Independence'),

(71, 'What territory did the United States buy from France in 1803?','the Louisiana Territory|Louisiana','American History','1800s'),
(72, 'Name one war fought by the United States in the 1800s.','War of 1812|Mexican-American War|Civil War|Spanish-American War','American History','1800s'),
(73, 'Name the U.S. war between the North and the South.','the Civil War|the War between the States','American History','1800s'),
(74, 'Name one problem that led to the Civil War.','slavery|economic reasons|states’ rights','American History','1800s'),
(75, 'What was one important thing that Abraham Lincoln did?','freed the slaves (Emancipation Proclamation)|saved (or preserved) the Union|led the United States during the Civil War','American History','1800s'),
(76, 'What did the Emancipation Proclamation do?','freed the slaves|freed slaves in the Confederacy|freed slaves in the Confederate states|freed slaves in most Southern states','American History','1800s'),
(77, 'What did Susan B. Anthony do?','fought for women’s rights|fought for civil rights','American History','1800s'),

(78, 'Name one war fought by the United States in the 1900s.','World War I|World War II|Korean War|Vietnam War|(Persian) Gulf War','American History','Recent American History and Other Important Historical Information'),
(79, 'Who was President during World War I?','(Woodrow) Wilson','American History','Recent American History and Other Important Historical Information'),
(80, 'Who was President during the Great Depression and World War II?','(Franklin) Roosevelt','American History','Recent American History and Other Important Historical Information'),
(81, 'Who did the United States fight in World War II?','Japan, Germany, and Italy','American History','Recent American History and Other Important Historical Information'),
(82, 'Before he was President, Eisenhower was a general. What war was he in?','World War II','American History','Recent American History and Other Important Historical Information'),
(83, 'During the Cold War, what was the main concern of the United States?','Communism','American History','Recent American History and Other Important Historical Information'),
(84, 'What movement tried to end racial discrimination?','civil rights (movement)','American History','Recent American History and Other Important Historical Information'),
(85, 'What did Martin Luther King, Jr. do?','fought for civil rights|worked for equality for all Americans','American History','Recent American History and Other Important Historical Information'),
(86, 'What major event happened on September 11, 2001, in the United States?','Terrorists attacked the United States.','American History','Recent American History and Other Important Historical Information'),
(87, 'Name one American Indian tribe in the United States.','Cherokee|Navajo|Sioux|Chippewa|Choctaw|Pueblo|Apache|Iroquois|Creek|Blackfeet|Seminole|Cheyenne|Arawak|Shawnee|Mohegan|Huron|Oneida|Lakota|Crow|Teton|Hopi|Inuit','American History','Recent American History and Other Important Historical Information'),

(88, 'Name one of the two longest rivers in the United States.','Missouri (River)|Mississippi (River)','Integrated Civics','Geography'),
(89, 'What ocean is on the West Coast of the United States?','Pacific (Ocean)','Integrated Civics','Geography'),
(90, 'What ocean is on the East Coast of the United States?','Atlantic (Ocean)','Integrated Civics','Geography'),
(91, 'Name one U.S. territory.','Puerto Rico|U.S. Virgin Islands|American Samoa|Northern Mariana Islands|Guam','Integrated Civics','Geography'),
(92, 'Name one state that borders Canada.','Maine|New Hampshire|Vermont|New York|Pennsylvania|Ohio|Michigan|Minnesota|North Dakota|Montana|Idaho|Washington|Alaska','Integrated Civics','Geography'),
(93, 'Name one state that borders Mexico.','California|Arizona|New Mexico|Texas','Integrated Civics','Geography'),
(94, 'What is the capital of the United States?','Washington, D.C.','Integrated Civics','Geography'),
(95, 'Where is the Statue of Liberty?','New York (Harbor)|Liberty Island|New Jersey|near New York City|on the Hudson (River)','Integrated Civics','Geography'),

(96, 'Why does the flag have 13 stripes?','because there were 13 original colonies|because the stripes represent the original colonies','Integrated Civics','Symbols'),
(97, 'Why does the flag have 50 stars?','because there is one star for each state|because each star represents a state|because there are 50 states','Integrated Civics','Symbols'),
(98, 'What is the name of the national anthem?','The Star-Spangled Banner','Integrated Civics','Symbols'),

(99, 'When do we celebrate Independence Day?','July 4','Integrated Civics','Holidays'),
(100, 'Name two national U.S. holidays.','New Year’s Day|Martin Luther King, Jr. Day|Presidents’ Day|Memorial Day|Independence Day|Labor Day|Columbus Day|Veterans Day|Thanksgiving|Christmas','Integrated Civics','Holidays');